manifest:
  version: "0.10"

  defaults:
    revision: main

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect/
    
    - name: lvgl
      revision: v8.0.1
      url-base: https://github.com/lvgl/lvgl
      path: modules/lib/gui/lvgl

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      path: nrf
      revision: master
      import: true

  self:
    path: skykey-firmware