manifest:
  version: 0.9

  defaults:
    revision: main

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect/

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      path: nrf
      revision: v1.5.1
      import: true
  
  self:
    path: skykey-firmware